import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    // ── 快速开始 ──
    {
      type: 'category',
      label: '快速开始',
      collapsible: true,
      collapsed: false,
      items: [
        { type: 'doc', id: 'getting-started/intro', label: '关于 LightClaw' },
        { type: 'doc', id: 'getting-started/installation', label: '安装指南' },
        { type: 'doc', id: 'getting-started/quickstart', label: '5 分钟上手' },
      ],
    },

    // ── 用户指南（自动生成：新增 .md 文件自动出现） ──
    {
      type: 'category',
      label: '用户指南',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: '核心功能',
          collapsed: false,
          items: [{ type: 'autogenerated', dirName: 'user-guide/core' }],
        },
        {
          type: 'category',
          label: '使用界面',
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'user-guide/ui' }],
        },
      ],
    },

    // ── 配置指南（自动生成） ──
    {
      type: 'category',
      label: '配置指南',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'category',
          label: '基础配置',
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'config/basic' }],
        },
        {
          type: 'category',
          label: '高级配置',
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'config/advanced' }],
        },
      ],
    },

    // ── 架构设计（自动生成） ──
    {
      type: 'category',
      label: '架构设计',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'category',
          label: '核心架构',
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'arch/core' }],
        },
        {
          type: 'category',
          label: '数据与安全',
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'arch/data-security' }],
        },
      ],
    },

    // ── 开发指南（自动生成） ──
    {
      type: 'category',
      label: '开发指南',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'category',
          label: '环境与项目',
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'dev/setup' }],
        },
        {
          type: 'category',
          label: '开发与贡献',
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'dev/contribute' }],
        },
      ],
    },
  ],
};

export default sidebars;
