import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // 完全自动生成：目录结构 = sidebar 结构
  // 目录名即分组名，中文 label 通过各目录下 _category_.json 设置
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
